# Generated by Django 4.2.3 on 2023-07-28 17:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('landmark_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='landmark_photo')),
                ('trip_time', models.CharField(max_length=100)),
            ],
        ),
    ]
