# Generated by Django 4.2.3 on 2023-07-31 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulgaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteLandmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulgaria.landmarks')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
