# Generated by Django 4.2.3 on 2023-07-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0002_favouritelandmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritelandmarks',
            name='landmark',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulgaria.landmarks'),
        ),
    ]
