# Generated by Django 4.1.1 on 2023-08-04 17:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulgaria', '0005_landmarks_accessibility_landmarks_additional_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lifespan', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('figure_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='figure_photo')),
                ('additional_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='additional photo')),
                ('unlock_quiz_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
