# Generated by Django 4.1.1 on 2023-08-04 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulgaria', '0007_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicfigure',
            name='unlocked_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
