# Generated by Django 4.1.1 on 2023-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0008_historicfigure_unlocked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='choice2_1',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice2_2',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice3_1',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='choice3_2',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_choice_2',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_choice_3',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question2',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question3',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
