# Generated by Django 4.1.1 on 2023-08-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0009_quizquestion_choice2_1_quizquestion_choice2_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice2_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice2_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice3_1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='choice3_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_choice_2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_choice_3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question3',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('choice_text2', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='bulgaria.quizquestion')),
            ],
        ),
    ]
