# Generated by Django 4.1.1 on 2023-08-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0010_rename_question_quizquestion_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text2',
        ),
    ]
