# Generated by Django 4.2.4 on 2023-08-10 19:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0012_remove_historicfigure_unlock_quiz_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicfigure',
            name='quote',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='additional_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='additional photo'),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover photo'),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='landmark_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='landmark photo'),
        ),
    ]
