# Generated by Django 4.2.4 on 2023-08-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulgaria', '0014_virtualfavouritelandmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualFavouriteLandmarks',
        ),
    ]
