# Generated by Django 4.2.3 on 2023-07-30 11:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useressentials_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useressentials',
            name='pfp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useressentials'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
